require 'slack-gamebot/api/endpoints/challenges_endpoint'
require 'slack-gamebot/api/endpoints/matches_endpoint'
require 'slack-gamebot/api/endpoints/users_endpoint'
require 'slack-gamebot/api/endpoints/seasons_endpoint'
require 'slack-gamebot/api/endpoints/root_endpoint'
