require 'slack-gamebot/models/elo'
require 'slack-gamebot/models/user'
require 'slack-gamebot/models/user_rank'
require 'slack-gamebot/models/challenge_state'
require 'slack-gamebot/models/challenge'
require 'slack-gamebot/models/score'
require 'slack-gamebot/models/match'
require 'slack-gamebot/models/season'
