name: lint

on: [push, pull_request]

jobs:
  RuboCop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.6"
          bundler-cache: true
      - run: bundle exec rubocop
